name: Login Test - Bash Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Run Login Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update WebDriver Manager
      run: |
        python -m pip install webdrivermanager --upgrade
        webdrivermanager chrome --linkpath /usr/local/bin

    - name: Run Bash Script
      run: |
        DATE_WITH_TIME=$(date "+%Y%m%d_%H%M%S")
        TESTS_PATH="$(pwd)/tests"
        cd "$TESTS_PATH"
        pytest -m login --alluredir "$TESTS_PATH/allure-report"

    - name: Archive Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: tests/allure-report
