name: Pre-commit and Smoke Tests Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  pre-commit-and-smoke-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Cache pip dependencies
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (including pre-commit)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run tests and generate Allure report
        run: |
          TESTS_PATH="$(pwd)/tests"
          ALLURE_REPORT_DIR="$TESTS_PATH/allure-report-${{ github.run_id }}-${{ github.run_number }}"
          cd "$TESTS_PATH"
          pytest -m smoke --alluredir "$ALLURE_REPORT_DIR"

      - name: Archive Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_id }}-${{ github.run_number }}
          path: tests/allure-report-${{ github.run_id }}-${{ github.run_number }}
